### ISSUE TITLE
Ability to set allowFullscreen attribute on iframe

### ISSUE THREAD

**Issue by rschick** [Brightspace/ifrau#77]
Capture video player has a full screen toggle button that doesn't work without the allowFullscreen attribute on the FRA iframe.

**Comment by HydeOnCoffee** [comment]
I also had the need of fullscreen option for my embedded react app. As I am new to git contributing I will start a pull request for my simple solution and hopefully dont do anything wrong. And btw thx brightspace for this little helper module. I use it with a react es2015 project code. with a little tweaking I got deep links working on my iframe.
